version: "3.9"

services:
  # eas-postgres:
  #   image: postgres:latest
  #   container_name: eas-postgres
  #   environment:
  #     POSTGRES_USER: postgres
  #     POSTGRES_PASSWORD: postgresPassword
  #     POSTGRES_DB: eas-index
  #   volumes:
  #     - postgres_data:/var/lib/postgresql/data
  #   ports:
  #     - "5432"

  eas-indexer:
    build: .
    container_name: eas_indexer_container
    environment:
      CHAIN_ID: ${CHAIN_ID}
      DATABASE_URL: "postgresql://htzTB5noUeQN:7Y1urVgpdWysKZfM@10.53.192.4:5432/credoracore"
    depends_on:
      - eas-postgres
    ports:
      - "4000:4000"

volumes:
  postgres_data:
